apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    labels:
        app.kubernetes.io/instance: pro-epargne-collab-ui
        app.kubernetes.io/name: pro-epargne-collab-ui
    name: pro-epargne-collab-ui
spec:
    dnsNames:
        - collab.pro-epargne.check-consulting.net
    issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: lets-encrypt-prd
    secretName: collab.pro-epargne.check-consulting.net.tls
    usages:
        - digital signature
        - key encipherment
